export const MOCK_RESPONSES = [
    {
        id: 'res_1',
        formId: 'form_1',
        formName: 'Customer Feedback',
        responder: 'John Doe',
        email: 'john.doe@example.com',
        createdAt: '2026-03-01T10:00:00Z',
        status: 'Completed',
        answers: {
            'Full Name': 'John Doe',
            'Email': 'john.doe@example.com',
            'Feedback': 'Great form! Very easy to use.',
            'Rating': 5,
        },
    },
    {
        id: 'res_2',
        formId: 'form_1',
        formName: 'Customer Feedback',
        responder: 'Jane Smith',
        email: 'jane.smith@example.com',
        createdAt: '2026-03-02T14:30:00Z',
        status: 'Completed',
        answers: {
            'Full Name': 'Jane Smith',
            'Email': 'jane.smith@example.com',
            'Feedback': 'Could use more options in the dropdown.',
            'Rating': 4,
        },
    },
    {
        id: 'res_3',
        formId: 'form_2',
        formName: 'User Survey',
        responder: 'Bob Wilson',
        email: 'bob.wilson@example.com',
        createdAt: '2026-03-05T09:15:00Z',
        status: 'Flagged',
        answers: {
            'Survey Question 1': 'Yes',
            'Suggestions': 'Maybe add a dark mode?',
        },
    },
    {
        id: 'res_4',
        formId: 'form_1',
        formName: 'Customer Feedback',
        responder: 'Alice Brown',
        email: 'alice.brown@example.com',
        createdAt: '2026-03-08T16:45:00Z',
        status: 'Completed',
        answers: {
            'Full Name': 'Alice Brown',
            'Email': 'alice.brown@example.com',
            'Feedback': 'Very professional design.',
            'Rating': 5,
        },
    },
    {
        id: 'res_5',
        formId: 'form_3',
        formName: 'Product Registration',
        responder: 'Charlie Davis',
        email: 'charlie.davis@example.com',
        createdAt: '2026-03-09T11:20:00Z',
        status: 'Processing',
        answers: {
            'Experience': 'Excellent',
            'Comments': 'I love the glassmorphism effect.',
        },
    },
    {
        id: 'res_6',
        formId: 'form_1',
        formName: 'Customer Feedback',
        responder: 'David Miller',
        email: 'david@example.com',
        createdAt: '2026-03-10T08:00:00Z',
        status: 'Completed',
        answers: {
            'Full Name': 'David Miller',
            'Email': 'david@example.com',
            'Feedback': 'Fast and reliable.',
            'Rating': 5,
        },
    },
    {
        id: 'res_7',
        formId: 'form_1',
        formName: 'Customer Feedback',
        responder: 'Eve Wilson',
        email: 'eve@example.com',
        createdAt: '2026-03-10T14:22:00Z',
        status: 'Pending',
        answers: {
            'Full Name': 'Eve Wilson',
            'Email': 'eve@example.com',
            'Feedback': 'Simple and clean.',
            'Rating': 4,
        },
    },
];

export const MOCK_ANALYTICS_STATS = {
    totalForms: 12,
    totalResponses: 156,
    activeUsers: 45,
    totalReports: 24,
    scheduledReports: 3,
    responsesPerPeriod: [
        { period: 'Mon', count: 12 },
        { period: 'Tue', count: 18 },
        { period: 'Wed', count: 20 },
        { period: 'Thu', count: 14 },
        { period: 'Fri', count: 25 },
        { period: 'Sat', count: 30 },
        { period: 'Sun', count: 37 },
    ],
};

export const MOCK_REPORTS = [
    {
        id: 'rep_1',
        name: 'Quarterly Feedback Summary',
        formId: 'form_1',
        formName: 'Customer Feedback',
        type: 'Summary',
        format: 'PDF',
        generatedAt: '2026-03-01T08:00:00Z',
        status: 'Completed',
    },
    {
        id: 'rep_2',
        name: 'User Engagement Deep Dive',
        formId: 'form_2',
        formName: 'User Survey',
        type: 'Detailed',
        format: 'CSV',
        generatedAt: '2026-03-05T14:30:00Z',
        status: 'Completed',
    },
    {
        id: 'rep_3',
        name: 'Weekly Performance Metrics',
        formId: 'form_1',
        formName: 'Customer Feedback',
        type: 'Analytics',
        format: 'JSON',
        generatedAt: '2026-03-09T10:15:00Z',
        status: 'Scheduled',
    },
    {
        id: 'rep_4',
        name: 'Registration Trend Analysis',
        formId: 'form_3',
        formName: 'Product Registration',
        type: 'Analytics',
        format: 'PDF',
        generatedAt: '2026-03-10T16:22:00Z',
        status: 'Completed',
    },
];
