export interface TemplateField {
  id: string
  fieldName: string
  label: string
  fieldValueType: string
  fieldType: string
  validation?: {
    required?: boolean
    minLength?: number
    maxLength?: number
    min?: number
    max?: number
    pattern?: string
  }
  placeholder?: string
  min?: number
  max?: number
  step?: number
  options?: Array<string>
}

export interface Template {
  id: string
  title: string
  description: string
  templateType: 'builtin' | 'custom'
  ownerId?: string
  fields: Array<TemplateField>
  createdAt: string
  updatedAt?: string
}

export const templatesApi = {
  getBuiltin: (): Promise<Array<Template>> => {
    return Promise.resolve(builtinTemplates)
  },
}

export const builtinTemplates: Array<Template> = [
  {
    id: 'builtin-admission',
    title: 'Admission Application Form',
    description:
      'Application form for university admissions with personal and academic details',
    templateType: 'builtin',
    createdAt: '2024-01-01T00:00:00Z',
    fields: [
      {
        id: 'f1',
        fieldName: 'fullName',
        label: 'Full Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true, minLength: 2, maxLength: 100 },
        placeholder: 'Enter your full name',
      },
      {
        id: 'f2',
        fieldName: 'dateOfBirth',
        label: 'Date of Birth',
        fieldValueType: 'string',
        fieldType: 'date',
        validation: { required: true },
      },
      {
        id: 'f3',
        fieldName: 'gender',
        label: 'Gender',
        fieldValueType: 'string',
        fieldType: 'radio',
        validation: { required: true },
        options: ['Male', 'Female', 'Other', 'Prefer not to say'],
      },
      {
        id: 'f4',
        fieldName: 'email',
        label: 'Email Address',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: {
          required: true,
          pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
        },
        placeholder: 'you@example.com',
      },
      {
        id: 'f5',
        fieldName: 'phone',
        label: 'Phone Number',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Your contact number',
      },
      {
        id: 'f6',
        fieldName: 'address',
        label: 'Permanent Address',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: true, maxLength: 500 },
        placeholder: 'Enter your full address',
      },
      {
        id: 'f7',
        fieldName: 'program',
        label: 'Program Applied For',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: [
          'B.Sc',
          'B.A',
          'B.Com',
          'B.Tech',
          'M.Sc',
          'M.A',
          'M.Com',
          'M.Tech',
          'Ph.D',
        ],
      },
      {
        id: 'f8',
        fieldName: 'department',
        label: 'Department',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: [
          'Computer Science',
          'Mathematics',
          'Physics',
          'Chemistry',
          'Biology',
          'Commerce',
          'Arts',
          'Engineering',
        ],
      },
      {
        id: 'f9',
        fieldName: 'highSchoolName',
        label: 'High School Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Name of your high school',
      },
      {
        id: 'f10',
        fieldName: 'highSchoolPercentage',
        label: 'High School Percentage/CGPA',
        fieldValueType: 'number',
        fieldType: 'number',
        validation: { required: true, min: 0, max: 100 },
        placeholder: 'Enter your percentage or CGPA',
      },
      {
        id: 'f11',
        fieldName: 'entranceExam',
        label: 'Entrance Exam Score',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: false },
        placeholder: 'Enter entrance exam score (if applicable)',
      },
      {
        id: 'f12',
        fieldName: 'parentName',
        label: 'Parent/Guardian Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Enter parent or guardian name',
      },
      {
        id: 'f13',
        fieldName: 'parentPhone',
        label: 'Parent/Guardian Phone',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Parent contact number',
      },
    ],
  },
  {
    id: 'builtin-course-registration',
    title: 'Course Registration',
    description: 'Form for students to register for courses each semester',
    templateType: 'builtin',
    createdAt: '2024-01-01T00:00:00Z',
    fields: [
      {
        id: 'f1',
        fieldName: 'studentId',
        label: 'Student ID',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Enter your student ID',
      },
      {
        id: 'f2',
        fieldName: 'fullName',
        label: 'Full Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Enter your full name',
      },
      {
        id: 'f3',
        fieldName: 'email',
        label: 'Email Address',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: {
          required: true,
          pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
        },
        placeholder: 'your.email@university.edu',
      },
      {
        id: 'f4',
        fieldName: 'semester',
        label: 'Semester',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: ['Fall 2024', 'Spring 2025', 'Summer 2025', 'Fall 2025'],
      },
      {
        id: 'f5',
        fieldName: 'year',
        label: 'Year',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: ['1st Year', '2nd Year', '3rd Year', '4th Year', '5th Year'],
      },
      {
        id: 'f6',
        fieldName: 'major',
        label: 'Major/Department',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: [
          'Computer Science',
          'Mathematics',
          'Physics',
          'Chemistry',
          'Biology',
          'Commerce',
          'Arts',
          'Engineering',
        ],
      },
      {
        id: 'f7',
        fieldName: 'courses',
        label: 'Courses to Register',
        fieldValueType: 'string',
        fieldType: 'checkbox',
        validation: { required: true },
        options: [
          'Course 101',
          'Course 102',
          'Course 103',
          'Course 104',
          'Course 105',
        ],
      },
      {
        id: 'f8',
        fieldName: 'additionalCourses',
        label: 'Additional Electives (Optional)',
        fieldValueType: 'string',
        fieldType: 'checkbox',
        validation: { required: false },
        options: ['Elective A', 'Elective B', 'Elective C'],
      },
      {
        id: 'f9',
        fieldName: 'remarks',
        label: 'Additional Remarks',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: false },
        placeholder: 'Any special requests or notes',
      },
    ],
  },
  {
    id: 'builtin-scholarship',
    title: 'Scholarship Application',
    description: 'Application form for student scholarships and financial aid',
    templateType: 'builtin',
    createdAt: '2024-01-01T00:00:00Z',
    fields: [
      {
        id: 'f1',
        fieldName: 'fullName',
        label: 'Full Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true, minLength: 2, maxLength: 100 },
        placeholder: 'Enter your full name',
      },
      {
        id: 'f2',
        fieldName: 'studentId',
        label: 'Student ID',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Enter your student ID',
      },
      {
        id: 'f3',
        fieldName: 'email',
        label: 'Email Address',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: {
          required: true,
          pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
        },
        placeholder: 'your.email@university.edu',
      },
      {
        id: 'f4',
        fieldName: 'phone',
        label: 'Phone Number',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Your contact number',
      },
      {
        id: 'f5',
        fieldName: 'program',
        label: 'Program of Study',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: [
          'B.Sc',
          'B.A',
          'B.Com',
          'B.Tech',
          'M.Sc',
          'M.A',
          'M.Com',
          'M.Tech',
          'Ph.D',
        ],
      },
      {
        id: 'f6',
        fieldName: 'year',
        label: 'Current Year',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: ['1st Year', '2nd Year', '3rd Year', '4th Year', '5th Year'],
      },
      {
        id: 'f7',
        fieldName: 'gpa',
        label: 'Current GPA/CGPA',
        fieldValueType: 'number',
        fieldType: 'number',
        validation: { required: true, min: 0, max: 10 },
        placeholder: 'Enter your GPA',
      },
      {
        id: 'f8',
        fieldName: 'scholarshipType',
        label: 'Scholarship Type',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: [
          'Merit-based',
          'Need-based',
          'Sports',
          'Research',
          'International',
        ],
      },
      {
        id: 'f9',
        fieldName: 'annualIncome',
        label: 'Annual Family Income',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: [
          'Below 1 Lakh',
          '1-3 Lakh',
          '3-5 Lakh',
          '5-10 Lakh',
          'Above 10 Lakh',
        ],
      },
      {
        id: 'f10',
        fieldName: 'previousScholarships',
        label: 'Have you received any scholarship before?',
        fieldValueType: 'boolean',
        fieldType: 'radio',
        validation: { required: true },
        options: ['Yes', 'No'],
      },
      {
        id: 'f11',
        fieldName: 'achievements',
        label: 'Academic Achievements',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: false },
        placeholder: 'List your notable achievements',
      },
      {
        id: 'f12',
        fieldName: 'financialNeed',
        label: 'Statement of Financial Need',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: false },
        placeholder: 'Explain your financial situation',
      },
    ],
  },
  {
    id: 'builtin-hostel',
    title: 'Hostel Allotment',
    description: 'Form for students to apply for hostel accommodation',
    templateType: 'builtin',
    createdAt: '2024-01-01T00:00:00Z',
    fields: [
      {
        id: 'f1',
        fieldName: 'fullName',
        label: 'Full Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Enter your full name',
      },
      {
        id: 'f2',
        fieldName: 'studentId',
        label: 'Student ID',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Enter your student ID',
      },
      {
        id: 'f3',
        fieldName: 'email',
        label: 'Email Address',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: {
          required: true,
          pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
        },
        placeholder: 'your.email@university.edu',
      },
      {
        id: 'f4',
        fieldName: 'phone',
        label: 'Phone Number',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Your contact number',
      },
      {
        id: 'f5',
        fieldName: 'program',
        label: 'Program',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: [
          'B.Sc',
          'B.A',
          'B.Com',
          'B.Tech',
          'M.Sc',
          'M.A',
          'M.Com',
          'M.Tech',
          'Ph.D',
        ],
      },
      {
        id: 'f6',
        fieldName: 'year',
        label: 'Year',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: ['1st Year', '2nd Year', '3rd Year', '4th Year', '5th Year'],
      },
      {
        id: 'f7',
        fieldName: 'hostelType',
        label: 'Preferred Hostel Type',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: [
          'AC Single',
          'AC Double',
          'Non-AC Single',
          'Non-AC Double',
          'Dormitory',
        ],
      },
      {
        id: 'f8',
        fieldName: 'roomPreference',
        label: 'Room Preference',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: ['Ground Floor', '1st Floor', '2nd Floor', 'No Preference'],
      },
      {
        id: 'f9',
        fieldName: 'permanentAddress',
        label: 'Permanent Address',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: true },
        placeholder: 'Enter your permanent address',
      },
      {
        id: 'f10',
        fieldName: 'distance',
        label: 'Distance from Home to University',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: [
          'Within 10 km',
          '10-50 km',
          '50-100 km',
          '100-500 km',
          'Above 500 km',
        ],
      },
      {
        id: 'f11',
        fieldName: 'medicalConditions',
        label: 'Medical Conditions (if any)',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: false },
        placeholder: 'List any medical conditions',
      },
      {
        id: 'f12',
        fieldName: 'emergencyContact',
        label: 'Emergency Contact Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Emergency contact person name',
      },
      {
        id: 'f13',
        fieldName: 'emergencyPhone',
        label: 'Emergency Contact Phone',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Emergency contact phone number',
      },
    ],
  },
  {
    id: 'builtin-course-feedback',
    title: 'Course Feedback Form',
    description: 'Students can provide feedback on courses and instructors',
    templateType: 'builtin',
    createdAt: '2024-01-01T00:00:00Z',
    fields: [
      {
        id: 'f1',
        fieldName: 'studentId',
        label: 'Student ID',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Enter your student ID',
      },
      {
        id: 'f2',
        fieldName: 'courseCode',
        label: 'Course Code',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'e.g., CS101',
      },
      {
        id: 'f3',
        fieldName: 'courseName',
        label: 'Course Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'e.g., Introduction to Computer Science',
      },
      {
        id: 'f4',
        fieldName: 'instructor',
        label: 'Instructor Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Name of your instructor',
      },
      {
        id: 'f5',
        fieldName: 'semester',
        label: 'Semester',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: ['Fall 2024', 'Spring 2025', 'Summer 2025', 'Fall 2025'],
      },
      {
        id: 'f6',
        fieldName: 'contentQuality',
        label: 'Course Content Quality',
        fieldValueType: 'number',
        fieldType: 'rating',
        validation: { required: true, min: 1, max: 5 },
      },
      {
        id: 'f7',
        fieldName: 'instructorRating',
        label: 'Instructor Effectiveness',
        fieldValueType: 'number',
        fieldType: 'rating',
        validation: { required: true, min: 1, max: 5 },
      },
      {
        id: 'f8',
        fieldName: 'teachingMethodology',
        label: 'Teaching Methodology',
        fieldValueType: 'string',
        fieldType: 'radio',
        validation: { required: true },
        options: ['Excellent', 'Good', 'Average', 'Needs Improvement', 'Poor'],
      },
      {
        id: 'f9',
        fieldName: 'courseMaterial',
        label: 'Course Materials (Textbooks, Notes)',
        fieldValueType: 'string',
        fieldType: 'radio',
        validation: { required: true },
        options: ['Very Helpful', 'Helpful', 'Neutral', 'Not Helpful'],
      },
      {
        id: 'f10',
        fieldName: 'assignments',
        label: 'Assignments and Assessments',
        fieldValueType: 'string',
        fieldType: 'radio',
        validation: { required: true },
        options: ['Excellent', 'Good', 'Average', 'Too Difficult', 'Too Easy'],
      },
      {
        id: 'f11',
        fieldName: 'learningOutcomes',
        label: 'Learning Outcomes Achieved',
        fieldValueType: 'number',
        fieldType: 'rating',
        validation: { required: true, min: 1, max: 5 },
      },
      {
        id: 'f12',
        fieldName: 'wouldRecommend',
        label: 'Would you recommend this course?',
        fieldValueType: 'boolean',
        fieldType: 'radio',
        validation: { required: true },
        options: ['Yes, definitely', 'Probably', 'Not sure', 'Probably not'],
      },
      {
        id: 'f13',
        fieldName: 'strengths',
        label: 'Course Strengths',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: false },
        placeholder: 'What did you like about this course?',
      },
      {
        id: 'f14',
        fieldName: 'improvements',
        label: 'Areas for Improvement',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: false },
        placeholder: 'What could be improved?',
      },
      {
        id: 'f15',
        fieldName: 'additionalComments',
        label: 'Additional Comments',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: false },
        placeholder: 'Any other feedback?',
      },
    ],
  },
  {
    id: 'builtin-contact',
    title: 'Contact Us Form',
    description: 'A simple contact form with name, email, and message fields',
    templateType: 'builtin',
    createdAt: '2024-01-01T00:00:00Z',
    fields: [
      {
        id: 'f1',
        fieldName: 'fullName',
        label: 'Full Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true, minLength: 2, maxLength: 100 },
        placeholder: 'Enter your full name',
      },
      {
        id: 'f2',
        fieldName: 'email',
        label: 'Email Address',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: {
          required: true,
          pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
        },
        placeholder: 'you@example.com',
      },
      {
        id: 'f3',
        fieldName: 'phone',
        label: 'Phone Number',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: false },
        placeholder: '(Optional) Your phone number',
      },
      {
        id: 'f4',
        fieldName: 'subject',
        label: 'Subject',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: ['General Inquiry', 'Support', 'Sales', 'Feedback', 'Other'],
      },
      {
        id: 'f5',
        fieldName: 'message',
        label: 'Message',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: true, minLength: 10, maxLength: 1000 },
        placeholder: 'How can we help you?',
      },
    ],
  },
  {
    id: 'builtin-feedback',
    title: 'Customer Feedback Form',
    description: 'Collect customer feedback with rating and suggestions',
    templateType: 'builtin',
    createdAt: '2024-01-01T00:00:00Z',
    fields: [
      {
        id: 'f1',
        fieldName: 'customerName',
        label: 'Your Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: false },
        placeholder: 'Enter your name (optional)',
      },
      {
        id: 'f2',
        fieldName: 'email',
        label: 'Email Address',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: {
          required: false,
          pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
        },
        placeholder: 'you@example.com (optional)',
      },
      {
        id: 'f3',
        fieldName: 'rating',
        label: 'How would you rate our service?',
        fieldValueType: 'number',
        fieldType: 'rating',
        validation: { required: true, min: 1, max: 5 },
      },
      {
        id: 'f4',
        fieldName: 'category',
        label: 'Feedback Category',
        fieldValueType: 'string',
        fieldType: 'radio',
        validation: { required: true },
        options: [
          'Product Quality',
          'Customer Service',
          'Website Experience',
          'Pricing',
          'Other',
        ],
      },
      {
        id: 'f5',
        fieldName: 'recommend',
        label: 'Would you recommend us to a friend?',
        fieldValueType: 'boolean',
        fieldType: 'radio',
        validation: { required: true },
        options: ['Yes, definitely', 'Maybe', 'No'],
      },
      {
        id: 'f6',
        fieldName: 'comments',
        label: 'Additional Comments',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: false, maxLength: 500 },
        placeholder: 'Share your detailed feedback...',
      },
    ],
  },
  {
    id: 'builtin-event-registration',
    title: 'Event Registration Form',
    description: 'Register participants for events with attendance details',
    templateType: 'builtin',
    createdAt: '2024-01-01T00:00:00Z',
    fields: [
      {
        id: 'f1',
        fieldName: 'fullName',
        label: 'Full Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true, minLength: 2, maxLength: 100 },
        placeholder: 'Enter your full name',
      },
      {
        id: 'f2',
        fieldName: 'email',
        label: 'Email Address',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: {
          required: true,
          pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
        },
        placeholder: 'you@example.com',
      },
      {
        id: 'f3',
        fieldName: 'phone',
        label: 'Phone Number',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Your contact number',
      },
      {
        id: 'f4',
        fieldName: 'organization',
        label: 'Organization/Company',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: false },
        placeholder: 'Your organization (optional)',
      },
      {
        id: 'f5',
        fieldName: 'attendanceType',
        label: 'Attendance Type',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: ['In-Person', 'Virtual', 'Both'],
      },
      {
        id: 'f6',
        fieldName: 'dietaryRestrictions',
        label: 'Dietary Restrictions',
        fieldValueType: 'string',
        fieldType: 'checkbox',
        validation: { required: false },
        options: ['Vegetarian', 'Vegan', 'Gluten-Free', 'Nut Allergy', 'None'],
      },
      {
        id: 'f7',
        fieldName: 'sessions',
        label: 'Sessions to Attend',
        fieldValueType: 'string',
        fieldType: 'checkbox',
        validation: { required: false },
        options: ['Morning Session', 'Afternoon Session', 'Evening Networking'],
      },
    ],
  },
  {
    id: 'builtin-job-application',
    title: 'Job Application Form',
    description: 'Collect resumes and applicant information for hiring',
    templateType: 'builtin',
    createdAt: '2024-01-01T00:00:00Z',
    fields: [
      {
        id: 'f1',
        fieldName: 'fullName',
        label: 'Full Name',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true, minLength: 2, maxLength: 100 },
        placeholder: 'Enter your full name',
      },
      {
        id: 'f2',
        fieldName: 'email',
        label: 'Email Address',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: {
          required: true,
          pattern: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
        },
        placeholder: 'you@example.com',
      },
      {
        id: 'f3',
        fieldName: 'phone',
        label: 'Phone Number',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: true },
        placeholder: 'Your contact number',
      },
      {
        id: 'f4',
        fieldName: 'currentCompany',
        label: 'Current Company',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: false },
        placeholder: 'Where do you currently work?',
      },
      {
        id: 'f5',
        fieldName: 'yearsOfExperience',
        label: 'Years of Experience',
        fieldValueType: 'number',
        fieldType: 'number',
        validation: { required: true, min: 0, max: 50 },
      },
      {
        id: 'f6',
        fieldName: 'position',
        label: 'Position Applying For',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: [
          'Software Engineer',
          'Product Manager',
          'Designer',
          'Data Analyst',
          'Other',
        ],
      },
      {
        id: 'f7',
        fieldName: 'linkedin',
        label: 'LinkedIn Profile',
        fieldValueType: 'string',
        fieldType: 'text',
        validation: { required: false },
        placeholder: 'https://linkedin.com/in/yourprofile',
      },
      {
        id: 'f8',
        fieldName: 'coverLetter',
        label: 'Cover Letter',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: false, maxLength: 2000 },
        placeholder: 'Tell us why you would be a great fit...',
      },
    ],
  },
  {
    id: 'builtin-survey',
    title: 'Customer Satisfaction Survey',
    description:
      'Measure customer satisfaction with NPS and detailed questions',
    templateType: 'builtin',
    createdAt: '2024-01-01T00:00:00Z',
    fields: [
      {
        id: 'f1',
        fieldName: 'productUsed',
        label: 'Which product/service did you use?',
        fieldValueType: 'string',
        fieldType: 'select',
        validation: { required: true },
        options: ['Product A', 'Product B', 'Product C', 'Multiple Products'],
      },
      {
        id: 'f2',
        fieldName: 'nps',
        label: 'How likely are you to recommend us to a friend? (0-10)',
        fieldValueType: 'number',
        fieldType: 'number',
        validation: { required: true, min: 0, max: 10 },
      },
      {
        id: 'f3',
        fieldName: 'easeOfUse',
        label: 'How easy was it to use our product?',
        fieldValueType: 'string',
        fieldType: 'radio',
        validation: { required: true },
        options: [
          'Very Easy',
          'Easy',
          'Neutral',
          'Difficult',
          'Very Difficult',
        ],
      },
      {
        id: 'f4',
        fieldName: 'supportRating',
        label: 'How would you rate our customer support?',
        fieldValueType: 'string',
        fieldType: 'radio',
        validation: { required: true },
        options: ['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'],
      },
      {
        id: 'f5',
        fieldName: 'improvements',
        label: 'What could we improve?',
        fieldValueType: 'string',
        fieldType: 'checkbox',
        validation: { required: false },
        options: [
          'Product Features',
          'User Interface',
          'Customer Support',
          'Pricing',
          'Documentation',
        ],
      },
      {
        id: 'f6',
        fieldName: 'additionalFeedback',
        label: 'Any other feedback?',
        fieldValueType: 'string',
        fieldType: 'textarea',
        validation: { required: false, maxLength: 500 },
        placeholder: 'Share any additional thoughts...',
      },
    ],
  },
]
