/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as EmailVerifiedRouteImport } from './routes/email-verified'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as FormFormIdRouteImport } from './routes/form.$formId'
import { Route as LayoutMyResponsesRouteImport } from './routes/_layout.my-responses'
import { Route as LayoutAnalyticsRouteImport } from './routes/_layout.analytics'
import { Route as LayoutEditorIndexRouteImport } from './routes/_layout.editor.index'
import { Route as LayoutAnalyticsIndexRouteImport } from './routes/_layout.analytics.index'
import { Route as LayoutEditorFormIdRouteImport } from './routes/_layout.editor.$formId'
import { Route as LayoutAnalyticsResponsesRouteImport } from './routes/_layout.analytics.responses'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifiedRoute = EmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const FormFormIdRoute = FormFormIdRouteImport.update({
  id: '/form/$formId',
  path: '/form/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutMyResponsesRoute = LayoutMyResponsesRouteImport.update({
  id: '/my-responses',
  path: '/my-responses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEditorIndexRoute = LayoutEditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsIndexRoute = LayoutAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAnalyticsRoute,
} as any)
const LayoutEditorFormIdRoute = LayoutEditorFormIdRouteImport.update({
  id: '/editor/$formId',
  path: '/editor/$formId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsResponsesRoute =
  LayoutAnalyticsResponsesRouteImport.update({
    id: '/responses',
    path: '/responses',
    getParentRoute: () => LayoutAnalyticsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof LayoutAnalyticsRouteWithChildren
  '/my-responses': typeof LayoutMyResponsesRoute
  '/form/$formId': typeof FormFormIdRoute
  '/analytics/responses': typeof LayoutAnalyticsResponsesRoute
  '/editor/$formId': typeof LayoutEditorFormIdRoute
  '/analytics/': typeof LayoutAnalyticsIndexRoute
  '/editor/': typeof LayoutEditorIndexRoute
}
export interface FileRoutesByTo {
  '/email-verified': typeof EmailVerifiedRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/my-responses': typeof LayoutMyResponsesRoute
  '/form/$formId': typeof FormFormIdRoute
  '/': typeof LayoutIndexRoute
  '/analytics/responses': typeof LayoutAnalyticsResponsesRoute
  '/editor/$formId': typeof LayoutEditorFormIdRoute
  '/analytics': typeof LayoutAnalyticsIndexRoute
  '/editor': typeof LayoutEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/email-verified': typeof EmailVerifiedRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_layout/analytics': typeof LayoutAnalyticsRouteWithChildren
  '/_layout/my-responses': typeof LayoutMyResponsesRoute
  '/form/$formId': typeof FormFormIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/analytics/responses': typeof LayoutAnalyticsResponsesRoute
  '/_layout/editor/$formId': typeof LayoutEditorFormIdRoute
  '/_layout/analytics/': typeof LayoutAnalyticsIndexRoute
  '/_layout/editor/': typeof LayoutEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-verified'
    | '/signin'
    | '/signup'
    | '/analytics'
    | '/my-responses'
    | '/form/$formId'
    | '/analytics/responses'
    | '/editor/$formId'
    | '/analytics/'
    | '/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/email-verified'
    | '/signin'
    | '/signup'
    | '/my-responses'
    | '/form/$formId'
    | '/'
    | '/analytics/responses'
    | '/editor/$formId'
    | '/analytics'
    | '/editor'
  id:
    | '__root__'
    | '/_layout'
    | '/email-verified'
    | '/signin'
    | '/signup'
    | '/_layout/analytics'
    | '/_layout/my-responses'
    | '/form/$formId'
    | '/_layout/'
    | '/_layout/analytics/responses'
    | '/_layout/editor/$formId'
    | '/_layout/analytics/'
    | '/_layout/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  EmailVerifiedRoute: typeof EmailVerifiedRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  FormFormIdRoute: typeof FormFormIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verified': {
      id: '/email-verified'
      path: '/email-verified'
      fullPath: '/email-verified'
      preLoaderRoute: typeof EmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/form/$formId': {
      id: '/form/$formId'
      path: '/form/$formId'
      fullPath: '/form/$formId'
      preLoaderRoute: typeof FormFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/my-responses': {
      id: '/_layout/my-responses'
      path: '/my-responses'
      fullPath: '/my-responses'
      preLoaderRoute: typeof LayoutMyResponsesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/editor/': {
      id: '/_layout/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof LayoutEditorIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics/': {
      id: '/_layout/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof LayoutAnalyticsIndexRouteImport
      parentRoute: typeof LayoutAnalyticsRoute
    }
    '/_layout/editor/$formId': {
      id: '/_layout/editor/$formId'
      path: '/editor/$formId'
      fullPath: '/editor/$formId'
      preLoaderRoute: typeof LayoutEditorFormIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics/responses': {
      id: '/_layout/analytics/responses'
      path: '/responses'
      fullPath: '/analytics/responses'
      preLoaderRoute: typeof LayoutAnalyticsResponsesRouteImport
      parentRoute: typeof LayoutAnalyticsRoute
    }
  }
}

interface LayoutAnalyticsRouteChildren {
  LayoutAnalyticsResponsesRoute: typeof LayoutAnalyticsResponsesRoute
  LayoutAnalyticsIndexRoute: typeof LayoutAnalyticsIndexRoute
}

const LayoutAnalyticsRouteChildren: LayoutAnalyticsRouteChildren = {
  LayoutAnalyticsResponsesRoute: LayoutAnalyticsResponsesRoute,
  LayoutAnalyticsIndexRoute: LayoutAnalyticsIndexRoute,
}

const LayoutAnalyticsRouteWithChildren = LayoutAnalyticsRoute._addFileChildren(
  LayoutAnalyticsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRouteWithChildren
  LayoutMyResponsesRoute: typeof LayoutMyResponsesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutEditorFormIdRoute: typeof LayoutEditorFormIdRoute
  LayoutEditorIndexRoute: typeof LayoutEditorIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAnalyticsRoute: LayoutAnalyticsRouteWithChildren,
  LayoutMyResponsesRoute: LayoutMyResponsesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutEditorFormIdRoute: LayoutEditorFormIdRoute,
  LayoutEditorIndexRoute: LayoutEditorIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  EmailVerifiedRoute: EmailVerifiedRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  FormFormIdRoute: FormFormIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
